apiVersion: v1
kind: Secret
metadata:
  name: ctfd-secrets
  namespace: ctfd
type: Opaque
stringData:
  DATABASE_URL: "mysql+pymysql://ctfd:ctfd123456@mariadb:3306/ctfd?charset=utf8mb4"
  SECRET_KEY: "ctfd123456"
  MYSQL_ROOT_PASSWORD: "ctfd123456"
  MYSQL_USER: "ctfd"
  MYSQL_PASSWORD: "ctfd123456"
  MYSQL_DATABASE: "ctfd"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: ctfd
type: Opaque
stringData:
  REDIS_URL: "redis://redis:6379"
