apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ctfd
  namespace: ctfd
  labels:
    app: ctfd
spec:
  to:
    kind: Service
    name: ctfd
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
